version: "3.9"
services:
  stevanio:
    profiles: [ "no-proxy" ]
    container_name: stevanio
    build:
      context: .
    expose:
      - 3000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
      - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
      - OPENAI_SB=$OPENAI_SB
    networks:
      - nginxproxy

  # chatgpt-next-web-proxy:
  #   profiles: [ "proxy" ]
  #   container_name: chatgpt-next-web-proxy
  #   image: yidadaa/chatgpt-next-web
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - OPENAI_API_KEY=$OPENAI_API_KEY
  #     - GOOGLE_API_KEY=$GOOGLE_API_KEY
  #     - CODE=$CODE
  #     - PROXY_URL=$PROXY_URL
  #     - BASE_URL=$BASE_URL
  #     - OPENAI_ORG_ID=$OPENAI_ORG_ID
  #     - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
  #     - DISABLE_GPT4=$DISABLE_GPT4
  #     - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
  #     - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
  #     - OPENAI_SB=$OPENAI_SB
  #   networks:
  #     - nginxproxy

networks:
  nginxproxy:
    external: true
